params(
[ {"name": "Animal Numbers", "value": "anmlnumxagg"},
{"name": "Livestock Feed Demand", "value": "qlxagg"},
{"name": "Total Yield", "value": "tyldxagg"},
{"name": "Animal Yield", "value": "anmlyldxagg"},
{"name": "Area", "value": "areaxagg"},
{"name": "Food Availability", "value": "foodavailxagg"},
{"name": "Income", "value": "gdpxagg"},
{"name": "World Prices", "value": "pwxagg"},
{"name": "Per capita Kilo-calorie Availability ", "value": "percapkcalxagg"},
{"name": "Population", "value": "popxagg"},
{"name": "Population at Risk of Hunger", "value": "populationatriskxagg"},
{"name": "Total Demand", "value": "qdxagg"},
{"name": "Export Share of Production", "value": "qeshxagg"},
{"name": "Household Demand", "value": "qfxagg"},
{"name": "Import Share of Demand", "value": "qmshxagg"},
{"name": "Net Trade Share of Production", "value": "qnsh1xagg"},
{"name": "Net Trade Share of Demand", "value": "qnsh2xagg"},
{"name": "Net Trade", "value": "qnxagg"},
{"name": "Commodity Supply", "value": "qsupxagg"},
{"name": "Total Area", "value": "tareaxagg"},
{"name": "Malnourished Children", "value": "totalmalnourishedxagg"},
{"name": "Yield", "value": "yldxagg"},
{"name": "Per Capita Income", "value": "pcgdpxagg"} ]
)
